### ISSUE TITLE
Problem importing Fido

### ISSUE THREAD

**Issue by yujin512** [bmorris3/stash#2]
Hi! 

I ran these lines: 
import matplotlib.pyplot as plt
from sunpy.net import Fido, attrs as a
from sunpy.map import Map

which gave me this:

Traceback (most recent call last):

  File "/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-5-3d59f1e14a3d>", line 2, in <module>
    from sunpy.net import Fido, attrs as a

  File "/anaconda3/lib/python3.6/site-packages/sunpy-0.9.0-py3.6-macosx-10.7-x86_64.egg/sunpy/net/__init__.py", line 5, in <module>
    from sunpy.net.fido_factory import Fido

  File "/anaconda3/lib/python3.6/site-packages/sunpy-0.9.0-py3.6-macosx-10.7-x86_64.egg/sunpy/net/fido_factory.py", line 20, in <module>
    from sunpy.net.dataretriever.clients import CLIENTS

  File "/anaconda3/lib/python3.6/site-packages/sunpy-0.9.0-py3.6-macosx-10.7-x86_64.egg/sunpy/net/dataretriever/__init__.py", line 11, in <module>
    from .client import QueryResponseBlock, QueryResponse, GenericClient

  File "/anaconda3/lib/python3.6/site-packages/sunpy-0.9.0-py3.6-macosx-10.7-x86_64.egg/sunpy/net/dataretriever/client.py", line 35, in <module>
    from sunpy.net.vso.attrs import Time, Wavelength, _Range

  File "/anaconda3/lib/python3.6/site-packages/sunpy-0.9.0-py3.6-macosx-10.7-x86_64.egg/sunpy/net/vso/__init__.py", line 4, in <module>
    from sunpy.net.vso.vso import VSOClient, InteractiveVSOClient, QueryResponse

  File "/anaconda3/lib/python3.6/site-packages/sunpy-0.9.0-py3.6-macosx-10.7-x86_64.egg/sunpy/net/vso/vso.py", line 32, in <module>
    from sunpy.net.proxyfix import WellBehavedHttpTransport

  File "/anaconda3/lib/python3.6/site-packages/sunpy-0.9.0-py3.6-macosx-10.7-x86_64.egg/sunpy/net/proxyfix.py", line 1, in <module>
    from suds.transport.http import HttpTransport as SudsHttpTransport

  File "/anaconda3/lib/python3.6/site-packages/suds/transport/http.py", line 63
    except u2.HTTPError, e:
                       ^
SyntaxError: invalid syntax

There were some problems with module client & suds not installed, so we manually installed them. We think there may be problems with Python, packages, and Anaconda being installed multiple times, so is there a way to uninstall and install everything? 
Thanks a lot!

**Comment by bmorris3** [comment]
If that still gives you problems, we can Skype and try to resolve them together in real time?

**Comment by yujin512** [comment]
Hi!! That'd be really helpful!! My Skype is leeyujin512. Message me when you are free to call!

**Comment by mbobra** [comment]
Hey @yujin512 @bmorris3 : we can use the [drms](https://drms.readthedocs.io/en/stable/) module to query SDO data instead of Fido. You can look at the examples there, or at [another example I wrote](https://nbviewer.jupyter.org/github/mbobra/calculating-spaceweather-keywords/blob/master/plot_swx_d3.ipynb). 

We can replace the query in the second code block of the ["Fetching an Image with Fido"](https://staff.washington.edu/bmmorris/stash/stash/gettingstarted.html#simulating-a-transit) example in Stash with the following:

```python
# Import the relevant modules
import drms
from astropy.io import fits

# Establish a connection to the database
c = drms.Client()

# Download the FITS header keywords and data arrays:
keys, segments = c.query('hmi.Ic_720s[2013.5.13_15:55]', key=drms.const.all, seg='continuum')
url_hmi = 'http://jsoc.stanford.edu' + segments.continuum[0]
downloaded_data = fits.getdata(url_hmi) 
```

**Comment by yujin512** [comment]
I installed sunpy[net], which includes suds-jurko, and now Fido is working!!!

**Comment by bmorris3** [comment]
Awesome! I'm glad to hear it =D
